package persistance.models;
// Generated 3 Nov, 2019 11:58:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="cs4227"
)
public class Users  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private char typeOfUser;

    public Users() {
    }

    public Users(String username, String password, char typeOfUser) {
       this.username = username;
       this.password = password;
       this.typeOfUser = typeOfUser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", nullable=false, length=15)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=15)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="typeOfUser", nullable=false, length=1)
    public char getTypeOfUser() {
        return this.typeOfUser;
    }
    
    public void setTypeOfUser(char typeOfUser) {
        this.typeOfUser = typeOfUser;
    }




}


